spring:
  datasource:
    url: jdbc:postgresql://84.38.183.185:5432/postgres
    username: postgres
    password: postfres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  rabbitmq:
    host: <hawk-01.rmq.cloudamqp.com>
    virtual-host: <tblsugde>
    port: 5672
    username: <tblsugde>
    password: <7G9KUXOqvCt3N1_3ZyuNEsSPBZNCsvjc>
    addresses: amqps://tblsugde:7G9KUXOqvCt3N1_3ZyuNEsSPBZNCsvjc@hawk.rmq.cloudamqp.com/tblsugde
#
#  security:
#    user:
#      name: dima
#      password: 123
logging:
  file:
    name: elk-stack.log