#spring:
#  datasource:
#    url: jdbc:postgresql://84.38.183.185:5432/postgres
#    username: postgres
#    password: postfres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show_sql: true
spring:
  datasource:
    url: jdbc:h2:~/data/productDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  rabbitmq:
    host: puffin.rmq2.cloudamqp.com
    virtual-host: ngzrlfjc
    port: 5672
    username: ngzrlfjc
    password: 1azq3GlaK90OCRt78skHLK-ikwYeZ4fE
    addresses: amqps://ngzrlfjc:1azq3GlaK90OCRt78skHLK-ikwYeZ4fE@puffin.rmq2.cloudamqp.com/ngzrlfjc
#
#  security:
#    user:
#      name: dima
#      password: 123